package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Perlengkapan;
import mysql.Koneksi;


public class FormPelengkapData extends javax.swing.JFrame {
    Perlengkapan perlengkapan;
    public ArrayList<Perlengkapan> getPerlengkapanList () {
        ArrayList<Perlengkapan> PerlengkapanList = new ArrayList<Perlengkapan>();
        Koneksi koneksi = new Koneksi();
        Connection connection = koneksi.getConnection();

        PreparedStatement ps;
        ResultSet rs;
        String query = "SELECT * From pelengkap_data";
        String order = " ORDER BY pelengkap_data.nim";
//        if(!keyword.equals(""))
//            query = query+ " WHERE anggota.id = ? OR nim like ?";

        query = query+order;
        try{
            ps = connection.prepareStatement(query);
//            if(!keyword.equals("")){
//                ps.setString(1,eCari.getText());
//                ps.setString(2, "%"+eCari.getText()+"%");
//            }
            rs = ps.executeQuery();
            while(rs.next()){
               perlengkapan = new Perlengkapan(
                        rs.getString("nim"),
                        rs.getString("nama_ayah"),
                        rs.getString("pekerjaan_ayah"),
                        rs.getString("nama_ibu"),
                       rs.getString("pekerjaan_ibu"),
                        rs.getString("alamat"));
                PerlengkapanList.add(perlengkapan);
            }
        } catch(SQLException ex){
            System.err.println("ERROR PerlengkapanList : "+ex);
            System.err.println(ex.getMessage());
        }
        return PerlengkapanList;
    } 
     public void selectPerlengkapan(){
        ArrayList<Perlengkapan> list;
        list = getPerlengkapanList();
        DefaultTableModel model = (DefaultTableModel)table2.getModel();
        Object[] row =  new Object[6];

        for (int i=0; i<list.size(); i++){
            row[0] = list.get(i).getNim();
            row[1] = list.get(i).getNamaayah();
            row[2] = list.get(i).getPekerjaanayah();
            row[3] = list.get(i).getNamaibu();
            row[4] = list.get(i).getPekerjaanibu();
            row[5] = list.get(i).getAlamat();
            model.addRow(row);
        }
    }
  public final void RefreshData(){
        DefaultTableModel  dtmbk = (DefaultTableModel) table2.getModel();
        dtmbk.setRowCount(0);
        selectPerlengkapan();
    }

    public final void resetForm(){
        fnim.setText("");
        fayah.setText("");
        fpayah.setText("");
        fibu.setText("");
        fpibu.setText("");
        falamat.setText("");
    }
   
    public FormPelengkapData() {
        initComponents();
        setLocationRelativeTo(null);
        RefreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaA = new javax.swing.JLabel();
        pAyah = new javax.swing.JLabel();
        namaI = new javax.swing.JLabel();
        pIbu = new javax.swing.JLabel();
        fayah = new javax.swing.JTextField();
        fpayah = new javax.swing.JTextField();
        fibu = new javax.swing.JTextField();
        fpibu = new javax.swing.JTextField();
        alamat = new javax.swing.JLabel();
        falamat = new javax.swing.JTextField();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        nim = new javax.swing.JLabel();
        fnim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perlengkapan Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        namaA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaA.setText("Nama Ayah");

        pAyah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pAyah.setText("Pekerjaan Ayah");

        namaI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        namaI.setText("Nama Ibu");

        pIbu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pIbu.setText("Pekerjaan Ibu");

        fpayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpayahActionPerformed(evt);
            }
        });

        alamat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alamat.setText("Alamat");

        Simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Keluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama Ayah", "Pekerjaan Ayah", "Nama Ibu", "Pekerjaan Ibu", "Alamat"
            }
        ));
        jScrollPane1.setViewportView(table2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        );

        nim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nim.setText("NIM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaA)
                                .addComponent(pAyah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(namaI, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pIbu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fpayah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fayah, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fibu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fpibu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(falamat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(Simpan)
                        .addGap(44, 44, 44)
                        .addComponent(Hapus)
                        .addGap(42, 42, 42)
                        .addComponent(Keluar)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nim)
                    .addComponent(fnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaA))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pAyah)
                    .addComponent(fpayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaI)
                    .addComponent(fibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIbu)
                    .addComponent(fpibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamat)
                    .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpan)
                    .addComponent(Hapus)
                    .addComponent(Keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fpayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpayahActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
         RefreshData();
    }//GEN-LAST:event_formWindowActivated

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        Perlengkapan perlengkapan = new Perlengkapan();
        perlengkapan.setNim(fnim.getText());
        perlengkapan.setNamaayah(fayah.getText());
        perlengkapan.setPekerjaanayah(fpayah.getText());
        perlengkapan.setNamaibu(fibu.getText());
        perlengkapan.setPekerjaanibu(fpibu.getText());
        perlengkapan.setAlamat(falamat.getText());

        if( fnim.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi data");
        }else{

            Koneksi koneksi = new Koneksi();
            Connection con = koneksi.getConnection();
            PreparedStatement ps;
            try {
                    String qry = "insert into pelengkap_data (nim,nama_ayah,pekerjaan_ayah,nama_ibu,pekerjaan_ibu,alamat) values (?,?,?,?,?,?)";

                        ps = con.prepareStatement(qry);
                        ps.setString(1, perlengkapan.getNim());
                        ps.setString(2, perlengkapan.getNamaayah());
                        ps.setString(3, perlengkapan.getPekerjaanayah());
                        ps.setString(4, perlengkapan.getNamaibu());
                        ps.setString(5, perlengkapan.getPekerjaanibu());
                        ps.setString(6,perlengkapan.getAlamat());
                        ps.executeUpdate();
                        RefreshData();
                        resetForm();
             }catch(SQLException e){
                System.err.println("error :"+e);
            }
        }

    }//GEN-LAST:event_SimpanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
         int i = table2.getSelectedRow();
        if(i>=0){
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "ingin dihapus ?",
                "Konfirmasi hapus",
                JOptionPane.YES_NO_OPTION);
        if(pilihan==0){
                try{
                    TableModel model = table2.getModel();
                    Koneksi koneksi = new Koneksi();
                    Connection con = koneksi.getConnection();
                    String executeQuery = "delete from pelengkap_data where nim=?";
                    PreparedStatement ps = con.prepareStatement(executeQuery);
                    ps.setString(1, model.getValueAt(i, 0).toString());
                    ps.executeUpdate();
                        RefreshData();
                        resetForm();
                }  catch (SQLException ex){
                    System.err.println(ex);
                }
            }
            }else{
                JOptionPane.showMessageDialog(null, "Pilih data yang ingin dihapus");
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        String tanya = "Apakah anda yakin akan keluar aplikasi?";
        boolean yakin = JOptionPane.showConfirmDialog(rootPane, tanya)
        == JOptionPane.YES_OPTION;
        if(yakin){
            System.exit(0);
        }
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelengkapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelengkapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelengkapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelengkapData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelengkapData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField falamat;
    private javax.swing.JTextField fayah;
    private javax.swing.JTextField fibu;
    private javax.swing.JTextField fnim;
    private javax.swing.JTextField fpayah;
    private javax.swing.JTextField fpibu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel namaA;
    private javax.swing.JLabel namaI;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel pAyah;
    private javax.swing.JLabel pIbu;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
